spring.application.name=BeautyStyle

#Configuración de la base de datos sql
spring.datasource.url =jdbc:mysql://localhost:3306/beautystyle_db?createDataBaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password =root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false